### ISSUE TITLE
sessionInit 未加入中间件列表时，若发生例外，依然会尝试调用 session，并且在某些情况下发生严重问题

### ISSUE THREAD

**Issue by Code-418** [top-think/framework#2251]
这个错误在特殊条件下，以及我遇到的时候的环境中，PHP 不返回任何错误，直接 Nginx 返回500。

测试时已透过命令行清理缓存，依然发生，下面是问题发生的情况

- 环境
  - PHP: 7.4.5
  - Nginx: 1.16.0

- 设置条件
  - 未将 SessionInit 类加入中间件使用列表文件，或是路由中
  - config/session.php 使用了遗留的错误设置，如下：
```php
return [
    'name'           => 'xxx_sid',
    'type'           => 'cache',
    'store'          => 'session',
    'expire'         => 0, // Never expire
];
```
但是cache中没有store为session的设置，不过因为未加入 session 中间件，理论上这个设置不应该有意义。session就不应该被使用。

- 发生条件
不确定其他情况，遇到的情况是 "Trying to get property 'xxx' of non-object" 的时候，但我估计是其他异常也会发生。

- 错误状况
会试图使用 session，在log中出现 "Store [session] not found." 错误，最后由 Nginx 直接返回500错误，PHP 没有返回应有的错误信息。下面是 PHP 的错误记录文件内的信息

```
[04-May-2020 00:07:09 Asia/Shanghai] PHP Fatal error:  Uncaught InvalidArgumentException: Store [session] not found. in <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php:69
Stack trace:
#0 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(74): think\Cache->getStoreConfig('session', 'type', 'file')
#1 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(126): think\Cache->resolveType('session')
#2 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Manager->createDriver('session')
#3 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('session')
#4 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(90): think\Manager->driver('session')
#5 <PROJECT_PATH>/vendor/topthink/framework/src/think/session/driver/Cache.php(31): think\Cache->store('session')
#6 [internal function]: think\session\driver\Cache->__construct(Object(think\Cache), Array)
#7 <PROJECT_PATH>/vendor/topthink/framework/src/think/Container.php(391): Ref in <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php on line 69
```

- 暂时解决处理
我直接拿掉了错误的 session 设置就 ok 了，至于是不是转去用了 session 默认的 file 设置就没有深究。

但是这个问题不应该发生的，没有设置 session 中间件理论上应该就别碰 session。可能是例外处理的地方有 bug？

**Comment by yunwuxin** [comment]
未加入session中间件 不代表你没使用session  肯定是你哪个地方使用了session  然后cache又没配置  当然会出错了

**Comment by Code-418** [comment]
> 未加入session中间件 不代表你没使用session 肯定是你哪个地方使用了session 然后cache又没配置 当然会出错了

全项目文件搜过了，没有使用任何 thinkphp 提供的session方法或类，虽然不相关，也没有使用 php 的session方法。而且这个问题只出现在例外的时候，是我在作一个新的类库的测试时刚好遇到的。没有例外就没有这个问题。

建议检查下例外处理的代码吧，虽然加班中没有去帮你们职位这个问题，我估计你们例外处理的地方后续生命周期流程在处理session，但是没有检查session的设置。

**Comment by yunwuxin** [comment]
你把上面的trace打印完整 就能看到哪里调用了session了

**Comment by Code-418** [comment]
> 你把上面的trace打印完整 就能看到哪里调用了session了

这边是问题已经pass过去了，回头看了一下error.log给你们发个bug report的。总之复现了问题打印给你吧。打印的log在下面的code block。

看了一下这个问题可能是例外发生的时候TP6框架直接搜集信息，捞session没做判断然后炸掉了。而且这个动作本身又产生例外，就套娃了。

下面的打印是套娃到挂为止的，只打印了 $e->getMessage() 跟 $e->getTraceAsString()。第一段不重要，只是我得引发例外才能踩到你们框架的这个问题。直接看第二段吧，#13从 think\exception\Handle 进到cache跟session的地方，应该这里是关键。

理论上没有开启的功能，其config应该就是无效的，写错也不应该有影响。而且炸到没得错误输出这个应该是不太对。不是很清楚这边你们的设计意图，如果没开启的功能config也必须是要正确的，那就建议当成是框架的特殊限制写在文档的配置章节中。

```
Manually threw exception.
#0 [internal function]: app\controller\Announce->get()
#1 <PROJECT_PATH>/vendor/topthink/framework/src/think/Container.php(327): ReflectionMethod->invokeArgs(Object(app\controller\Announce), Array)
#2 <PROJECT_PATH>/vendor/topthink/framework/src/think/Container.php(360): think\Container->invokeMethod('get', Array, false)
#3 <PROJECT_PATH>/vendor/topthink/framework/src/think/route/dispatch/Callback.php(27): think\Container->invoke(Array, Array)
#4 <PROJECT_PATH>/vendor/topthink/framework/src/think/route/Dispatch.php(96): think\route\dispatch\Callback->exec()
#5 <PROJECT_PATH>/vendor/topthink/framework/src/think/Route.php(747): think\route\Dispatch->run()
#6 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(59): think\Route->think\{closure}(Object(app\Request))
#7 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(65): think\Pipeline->think\{closure}(Object(app\Request))
#8 <PROJECT_PATH>/vendor/topthink/framework/src/think/Route.php(748): think\Pipeline->then(Object(Closure))
#9 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(213): think\Route->dispatch(Object(app\Request), Object(Closure))
#10 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(203): think\Http->dispatchToRoute(Object(app\Request))
#11 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(59): think\Http->think\{closure}(Object(app\Request))
#12 <PROJECT_PATH>/app/middleware/Auth.php(38): think\Pipeline->think\{closure}(Object(app\Request))
#13 [internal function]: app\middleware\Auth->handle(Object(app\Request), Object(Closure))
#14 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func(Array, Object(app\Request), Object(Closure))
#15 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(84): think\Middleware->think\{closure}(Object(app\Request), Object(Closure))
#16 <PROJECT_PATH>/app/middleware/InputDecrypt.php(40): think\Pipeline->think\{closure}(Object(app\Request))
#17 [internal function]: app\middleware\InputDecrypt->handle(Object(app\Request), Object(Closure))
#18 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func(Array, Object(app\Request), Object(Closure))
#19 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(84): think\Middleware->think\{closure}(Object(app\Request), Object(Closure))
#20 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(65): think\Pipeline->think\{closure}(Object(app\Request))
#21 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(204): think\Pipeline->then(Object(Closure))
#22 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(162): think\Http->runWithRequest(Object(app\Request))
#23 <PROJECT_PATH>/public/index.php(11): think\Http->run()
#24 {main}

Store [session] not found.
#0 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(74): think\Cache->getStoreConfig('session', 'type', 'file')
#1 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(126): think\Cache->resolveType('session')
#2 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Manager->createDriver('session')
#3 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('session')
#4 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(90): think\Manager->driver('session')
#5 <PROJECT_PATH>/vendor/topthink/framework/src/think/session/driver/Cache.php(31): think\Cache->store('session')
#6 [internal function]: think\session\driver\Cache->__construct(Object(think\Cache), Array)
#7 <PROJECT_PATH>/vendor/topthink/framework/src/think/Container.php(391): ReflectionClass->newInstanceArgs(Array)
#8 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(138): think\Container->invokeClass('\\think\\session\\...', Array)
#9 <PROJECT_PATH>/vendor/topthink/framework/src/think/Session.php(29): think\Manager->createDriver('cache')
#10 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Session->createDriver('cache')
#11 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('cache')
#12 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(174): think\Manager->driver()
#13 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(178): think\Manager->__call('all', Array)
#14 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(224): think\exception\Handle->convertExceptionToArray(Object(Error))
#15 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(208): think\exception\Handle->renderExceptionContent(Object(Error))
#16 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(111): think\exception\Handle->convertExceptionToResponse(Object(Error))
#17 <PROJECT_PATH>/app/ExceptionHandle.php(76): think\exception\Handle->render(Object(app\Request), Object(Error))
#18 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(185): app\ExceptionHandle->render(Object(app\Request), Object(Error))
#19 [internal function]: think\Middleware->handleException(Object(app\Request), Object(Error))
#20 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(101): call_user_func(Array, Object(app\Request), Object(Error))
#21 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(61): think\Pipeline->handleException(Object(app\Request), Object(Error))
#22 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(65): think\Pipeline->think\{closure}(Object(app\Request))
#23 <PROJECT_PATH>/vendor/topthink/framework/src/think/Route.php(748): think\Pipeline->then(Object(Closure))
#24 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(213): think\Route->dispatch(Object(app\Request), Object(Closure))
#25 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(203): think\Http->dispatchToRoute(Object(app\Request))
#26 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(59): think\Http->think\{closure}(Object(app\Request))
#27 <PROJECT_PATH>/app/middleware/Auth.php(38): think\Pipeline->think\{closure}(Object(app\Request))
#28 [internal function]: app\middleware\Auth->handle(Object(app\Request), Object(Closure))
#29 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func(Array, Object(app\Request), Object(Closure))
#30 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(84): think\Middleware->think\{closure}(Object(app\Request), Object(Closure))
#31 <PROJECT_PATH>/app/middleware/InputDecrypt.php(40): think\Pipeline->think\{closure}(Object(app\Request))
#32 [internal function]: app\middleware\InputDecrypt->handle(Object(app\Request), Object(Closure))
#33 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func(Array, Object(app\Request), Object(Closure))
#34 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(84): think\Middleware->think\{closure}(Object(app\Request), Object(Closure))
#35 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(65): think\Pipeline->think\{closure}(Object(app\Request))
#36 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(204): think\Pipeline->then(Object(Closure))
#37 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(162): think\Http->runWithRequest(Object(app\Request))
#38 <PROJECT_PATH>/public/index.php(11): think\Http->run()
#39 {main}

Store [session] not found.
#0 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(74): think\Cache->getStoreConfig('session', 'type', 'file')
#1 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(126): think\Cache->resolveType('session')
#2 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Manager->createDriver('session')
#3 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('session')
#4 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(90): think\Manager->driver('session')
#5 <PROJECT_PATH>/vendor/topthink/framework/src/think/session/driver/Cache.php(31): think\Cache->store('session')
#6 [internal function]: think\session\driver\Cache->__construct(Object(think\Cache), Array)
#7 <PROJECT_PATH>/vendor/topthink/framework/src/think/Container.php(391): ReflectionClass->newInstanceArgs(Array)
#8 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(138): think\Container->invokeClass('\\think\\session\\...', Array)
#9 <PROJECT_PATH>/vendor/topthink/framework/src/think/Session.php(29): think\Manager->createDriver('cache')
#10 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Session->createDriver('cache')
#11 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('cache')
#12 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(174): think\Manager->driver()
#13 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(178): think\Manager->__call('all', Array)
#14 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(224): think\exception\Handle->convertExceptionToArray(Object(InvalidArgumentException))
#15 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(208): think\exception\Handle->renderExceptionContent(Object(InvalidArgumentException))
#16 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(111): think\exception\Handle->convertExceptionToResponse(Object(InvalidArgumentException))
#17 <PROJECT_PATH>/app/ExceptionHandle.php(76): think\exception\Handle->render(Object(app\Request), Object(InvalidArgumentException))
#18 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(185): app\ExceptionHandle->render(Object(app\Request), Object(InvalidArgumentException))
#19 [internal function]: think\Middleware->handleException(Object(app\Request), Object(InvalidArgumentException))
#20 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(101): call_user_func(Array, Object(app\Request), Object(InvalidArgumentException))
#21 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(61): think\Pipeline->handleException(Object(app\Request), Object(InvalidArgumentException))
#22 <PROJECT_PATH>/app/middleware/Auth.php(38): think\Pipeline->think\{closure}(Object(app\Request))
#23 [internal function]: app\middleware\Auth->handle(Object(app\Request), Object(Closure))
#24 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func(Array, Object(app\Request), Object(Closure))
#25 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(84): think\Middleware->think\{closure}(Object(app\Request), Object(Closure))
#26 <PROJECT_PATH>/app/middleware/InputDecrypt.php(40): think\Pipeline->think\{closure}(Object(app\Request))
#27 [internal function]: app\middleware\InputDecrypt->handle(Object(app\Request), Object(Closure))
#28 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func(Array, Object(app\Request), Object(Closure))
#29 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(84): think\Middleware->think\{closure}(Object(app\Request), Object(Closure))
#30 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(65): think\Pipeline->think\{closure}(Object(app\Request))
#31 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(204): think\Pipeline->then(Object(Closure))
#32 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(162): think\Http->runWithRequest(Object(app\Request))
#33 <PROJECT_PATH>/public/index.php(11): think\Http->run()
#34 {main}

Store [session] not found.
#0 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(74): think\Cache->getStoreConfig('session', 'type', 'file')
#1 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(126): think\Cache->resolveType('session')
#2 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Manager->createDriver('session')
#3 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('session')
#4 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(90): think\Manager->driver('session')
#5 <PROJECT_PATH>/vendor/topthink/framework/src/think/session/driver/Cache.php(31): think\Cache->store('session')
#6 [internal function]: think\session\driver\Cache->__construct(Object(think\Cache), Array)
#7 <PROJECT_PATH>/vendor/topthink/framework/src/think/Container.php(391): ReflectionClass->newInstanceArgs(Array)
#8 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(138): think\Container->invokeClass('\\think\\session\\...', Array)
#9 <PROJECT_PATH>/vendor/topthink/framework/src/think/Session.php(29): think\Manager->createDriver('cache')
#10 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Session->createDriver('cache')
#11 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('cache')
#12 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(174): think\Manager->driver()
#13 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(178): think\Manager->__call('all', Array)
#14 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(224): think\exception\Handle->convertExceptionToArray(Object(InvalidArgumentException))
#15 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(208): think\exception\Handle->renderExceptionContent(Object(InvalidArgumentException))
#16 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(111): think\exception\Handle->convertExceptionToResponse(Object(InvalidArgumentException))
#17 <PROJECT_PATH>/app/ExceptionHandle.php(76): think\exception\Handle->render(Object(app\Request), Object(InvalidArgumentException))
#18 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(185): app\ExceptionHandle->render(Object(app\Request), Object(InvalidArgumentException))
#19 [internal function]: think\Middleware->handleException(Object(app\Request), Object(InvalidArgumentException))
#20 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(101): call_user_func(Array, Object(app\Request), Object(InvalidArgumentException))
#21 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(86): think\Pipeline->handleException(Object(app\Request), Object(InvalidArgumentException))
#22 <PROJECT_PATH>/app/middleware/InputDecrypt.php(40): think\Pipeline->think\{closure}(Object(app\Request))
#23 [internal function]: app\middleware\InputDecrypt->handle(Object(app\Request), Object(Closure))
#24 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func(Array, Object(app\Request), Object(Closure))
#25 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(84): think\Middleware->think\{closure}(Object(app\Request), Object(Closure))
#26 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(65): think\Pipeline->think\{closure}(Object(app\Request))
#27 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(204): think\Pipeline->then(Object(Closure))
#28 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(162): think\Http->runWithRequest(Object(app\Request))
#29 <PROJECT_PATH>/public/index.php(11): think\Http->run()
#30 {main}

Store [session] not found.
#0 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(74): think\Cache->getStoreConfig('session', 'type', 'file')
#1 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(126): think\Cache->resolveType('session')
#2 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Manager->createDriver('session')
#3 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('session')
#4 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(90): think\Manager->driver('session')
#5 <PROJECT_PATH>/vendor/topthink/framework/src/think/session/driver/Cache.php(31): think\Cache->store('session')
#6 [internal function]: think\session\driver\Cache->__construct(Object(think\Cache), Array)
#7 <PROJECT_PATH>/vendor/topthink/framework/src/think/Container.php(391): ReflectionClass->newInstanceArgs(Array)
#8 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(138): think\Container->invokeClass('\\think\\session\\...', Array)
#9 <PROJECT_PATH>/vendor/topthink/framework/src/think/Session.php(29): think\Manager->createDriver('cache')
#10 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Session->createDriver('cache')
#11 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('cache')
#12 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(174): think\Manager->driver()
#13 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(178): think\Manager->__call('all', Array)
#14 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(224): think\exception\Handle->convertExceptionToArray(Object(InvalidArgumentException))
#15 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(208): think\exception\Handle->renderExceptionContent(Object(InvalidArgumentException))
#16 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(111): think\exception\Handle->convertExceptionToResponse(Object(InvalidArgumentException))
#17 <PROJECT_PATH>/app/ExceptionHandle.php(76): think\exception\Handle->render(Object(app\Request), Object(InvalidArgumentException))
#18 <PROJECT_PATH>/vendor/topthink/framework/src/think/Middleware.php(185): app\ExceptionHandle->render(Object(app\Request), Object(InvalidArgumentException))
#19 [internal function]: think\Middleware->handleException(Object(app\Request), Object(InvalidArgumentException))
#20 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(101): call_user_func(Array, Object(app\Request), Object(InvalidArgumentException))
#21 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(86): think\Pipeline->handleException(Object(app\Request), Object(InvalidArgumentException))
#22 <PROJECT_PATH>/vendor/topthink/framework/src/think/Pipeline.php(65): think\Pipeline->think\{closure}(Object(app\Request))
#23 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(204): think\Pipeline->then(Object(Closure))
#24 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(162): think\Http->runWithRequest(Object(app\Request))
#25 <PROJECT_PATH>/public/index.php(11): think\Http->run()
#26 {main}

Store [session] not found.
#0 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(74): think\Cache->getStoreConfig('session', 'type', 'file')
#1 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(126): think\Cache->resolveType('session')
#2 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Manager->createDriver('session')
#3 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('session')
#4 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(90): think\Manager->driver('session')
#5 <PROJECT_PATH>/vendor/topthink/framework/src/think/session/driver/Cache.php(31): think\Cache->store('session')
#6 [internal function]: think\session\driver\Cache->__construct(Object(think\Cache), Array)
#7 <PROJECT_PATH>/vendor/topthink/framework/src/think/Container.php(391): ReflectionClass->newInstanceArgs(Array)
#8 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(138): think\Container->invokeClass('\\think\\session\\...', Array)
#9 <PROJECT_PATH>/vendor/topthink/framework/src/think/Session.php(29): think\Manager->createDriver('cache')
#10 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Session->createDriver('cache')
#11 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('cache')
#12 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(174): think\Manager->driver()
#13 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(178): think\Manager->__call('all', Array)
#14 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(224): think\exception\Handle->convertExceptionToArray(Object(InvalidArgumentException))
#15 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(208): think\exception\Handle->renderExceptionContent(Object(InvalidArgumentException))
#16 <PROJECT_PATH>/vendor/topthink/framework/src/think/exception/Handle.php(111): think\exception\Handle->convertExceptionToResponse(Object(InvalidArgumentException))
#17 <PROJECT_PATH>/app/ExceptionHandle.php(76): think\exception\Handle->render(Object(app\Request), Object(InvalidArgumentException))
#18 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(266): app\ExceptionHandle->render(Object(app\Request), Object(InvalidArgumentException))
#19 <PROJECT_PATH>/vendor/topthink/framework/src/think/Http.php(166): think\Http->renderException(Object(app\Request), Object(InvalidArgumentException))
#20 <PROJECT_PATH>/public/index.php(11): think\Http->run()
#21 {main}

Uncaught InvalidArgumentException: Store [session] not found. in <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php:69
Stack trace:
#0 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(74): think\Cache->getStoreConfig('session', 'type', 'file')
#1 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(126): think\Cache->resolveType('session')
#2 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(65): think\Manager->createDriver('session')
#3 <PROJECT_PATH>/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('session')
#4 <PROJECT_PATH>/vendor/topthink/framework/src/think/Cache.php(90): think\Manager->driver('session')
#5 <PROJECT_PATH>/vendor/topthink/framework/src/think/session/driver/Cache.php(31): think\Cache->store('session')
#6 [internal function]: think\session\driver\Cache->__construct(Object(think\Cache), Array)
#7 <PROJECT_PATH>/vendor/topthink/framework/src/think/Container.php(391): Ref
#0 [internal function]: think\initializer\Error->appShutdown()
#1 {main}
```

**Comment by yunwuxin** [comment]
https://github.com/top-think/framework/blob/1f8ed5ee845c67b2e8406e1a79f23ce0c50c5f04/src/think/exception/Handle.php#L178

这里获取session数据的时候是做了判断的，只有app里存在session实例的时候 才会搜集session的数据

你们项目里肯定是有地方使用了session，哪怕是依赖注入了没有使用，也算使用了

项目里没有，再看看引用的其他composer包里是不是使用了

**Comment by Code-418** [comment]
> https://github.com/top-think/framework/blob/1f8ed5ee845c67b2e8406e1a79f23ce0c50c5f04/src/think/exception/Handle.php#L178
> 
> 这里获取session数据的时候是做了判断的，只有app里存在session实例的时候 才会搜集session的数据
> 
> 你们项目里肯定是有地方使用了session，哪怕是依赖注入了没有使用，也算使用了
> 
> 项目里没有，再看看引用的其他composer包里是不是使用了

刚刚直接composer create了干净的新的 thinkphp 6.0.2 项目来测试，没有加任何其他包跟代码。

加入了使用了不存在的 store 的错误 session 配置，就是issue本文的那个，以及加入了 .env，里头只有一行 APP_DEBUG = true ，然后随便搞一个例外出来，问题就复现了。

由于是干净的新项目，没有其他东西，应该就只是这个地方的处理有问题，你们可以这样复现看看。

**Comment by yunwuxin** [comment]
是这个提交里修正的  https://github.com/top-think/framework/commit/dbe7e9d7159d767b37c05627069289a07138e13e

还没有release

**Comment by Code-418** [comment]
> 是这个提交里修正的 [dbe7e9d](https://github.com/top-think/framework/commit/dbe7e9d7159d767b37c05627069289a07138e13e)
> 
> 还没有release

理解，是已发现的问题那就没事了，谢谢
