### ISSUE TITLE
[v6.0.6] 更新后导致部分路由解析错误

### ISSUE THREAD

**Issue by NHZEX** [top-think/framework#2454]
1. 定义以下路由：
```php
\app()->route->get('api/orders/<id>/order', 'api/test');
```

2. 访问地址：```http://bug.test/api/orders/10/order```

3. 产生错误堆栈信息：
```
Class: \think\Exception
Error: [0] route pattern error
File : /vendor/topthink/framework/src/think/route/RuleItem.php:299
#0 /vendor/topthink/framework/src/think/route/RuleItem.php(199): think\route\RuleItem->match()
#1 /vendor/topthink/framework/src/think/route/RuleItem.php(219): think\route\RuleItem->checkRule()
#2 /vendor/topthink/framework/src/think/route/RuleGroup.php(167): think\route\RuleItem->check()
#3 /vendor/topthink/framework/src/think/route/Domain.php(62): think\route\RuleGroup->check()
#4 /vendor/topthink/framework/src/think/Route.php(789): think\route\Domain->check()
#5 /vendor/topthink/framework/src/think/Route.php(762): think\Route->check()
#6 /vendor/topthink/framework/src/think/Http.php(216): think\Route->dispatch()
#7 /vendor/topthink/framework/src/think/Http.php(206): think\Http->dispatchToRoute()
#8 /vendor/topthink/framework/src/think/Pipeline.php(59): think\Http->think\{closure}()
#9 /app/Service/Auth/Middleware/SessionInit.php(63): think\Pipeline->think\{closure}()
#10 [internal function]: app\Service\Auth\Middleware\SessionInit->handle()
#11 /vendor/topthink/framework/src/think/Middleware.php(142): call_user_func()
#12 /vendor/topthink/framework/src/think/Pipeline.php(85): think\Middleware->think\{closure}()
#13 /vendor/topthink/framework/src/think/Pipeline.php(66): think\Pipeline->think\{closure}()
#14 /vendor/topthink/framework/src/think/Http.php(207): think\Pipeline->then()
#15 /vendor/topthink/framework/src/think/Http.php(170): think\Http->runWithRequest()
#16 /public/index.php(22): think\Http->run()
#17 {main}
Class: \think\exception\ErrorException
Error: [0] preg_match(): Unknown modifier 'o'
File : /vendor/topthink/framework/src/think/route/RuleItem.php:295
#0 [internal function]: think\initializer\Error->appError()
#1 /vendor/topthink/framework/src/think/route/RuleItem.php(295): preg_match()
#2 /vendor/topthink/framework/src/think/route/RuleItem.php(199): think\route\RuleItem->match()
#3 /vendor/topthink/framework/src/think/route/RuleItem.php(219): think\route\RuleItem->checkRule()
#4 /vendor/topthink/framework/src/think/route/RuleGroup.php(167): think\route\RuleItem->check()
#5 /vendor/topthink/framework/src/think/route/Domain.php(62): think\route\RuleGroup->check()
#6 /vendor/topthink/framework/src/think/Route.php(789): think\route\Domain->check()
#7 /vendor/topthink/framework/src/think/Route.php(762): think\Route->check()
#8 /vendor/topthink/framework/src/think/Http.php(216): think\Route->dispatch()
#9 /vendor/topthink/framework/src/think/Http.php(206): think\Http->dispatchToRoute()
#10 /vendor/topthink/framework/src/think/Pipeline.php(59): think\Http->think\{closure}()
#11 /app/Service/Auth/Middleware/SessionInit.php(63): think\Pipeline->think\{closure}()
#12 [internal function]: app\Service\Auth\Middleware\SessionInit->handle()
#13 /vendor/topthink/framework/src/think/Middleware.php(142): call_user_func()
#14 /vendor/topthink/framework/src/think/Pipeline.php(85): think\Middleware->think\{closure}()
#15 /vendor/topthink/framework/src/think/Pipeline.php(66): think\Pipeline->think\{closure}()
#16 /vendor/topthink/framework/src/think/Http.php(207): think\Pipeline->then()
#17 /vendor/topthink/framework/src/think/Http.php(170): think\Http->runWithRequest()
#18 /public/index.php(22): think\Http->run()
#19 {main}
```

4. 问题产生原因是由于这个修改：
https://github.com/top-think/framework/blob/c878ece31cd9bd8f2b1e5f01292bfc40625db945/src/think/route/Rule.php#L808-L810
使`/orders`被替换两次，产生`\`模式分隔符导致正则提前被截断

5. 建议使用`~`替代`\`作为正则模式分隔符，

**Comment by liu21st** [comment]
这个问题改进了下 可以用开发版重新测试下

**Comment by NHZEX** [comment]
测试下，用开发版没有问题了

**Comment by NHZEX** [comment]
fixes: `v6.0.7`
