### ISSUE TITLE
完蛋了。。Upgrading topthink/framework (v6.0.7 c2b477b => v6.0.7 db8fe22)

### ISSUE THREAD

**Issue by hulang** [top-think/framework#2466]
更新这个版本后网站挂了。
[28-Jan-2021 11:10:51 UTC] PHP Fatal error:  Uncaught ReflectionException: Class think\Config does not exist in D:\laragon\www\blog\vendor\topthink\framework\src\think\Container.php:375
Stack trace:
#0 D:\laragon\www\blog\vendor\topthink\framework\src\think\Container.php(375): ReflectionClass->__construct('think\\Config')
#1 D:\laragon\www\blog\vendor\topthink\framework\src\think\Container.php(251): think\Container->invokeClass('think\\Config', Array)
#2 D:\laragon\www\blog\vendor\topthink\framework\src\think\Container.php(130): think\Container->make('think\\Config')
#3 D:\laragon\www\blog\vendor\topthink\framework\src\think\Container.php(510): think\Container->get('config')
#4 D:\laragon\www\blog\vendor\topthink\framework\src\think\App.php(511): think\Container->__get('config')
#5 D:\laragon\www\blog\vendor\topthink\framework\src\think\App.php(420): think\App->load()
#6 D:\laragon\www\blog\vendor\topthink\framework\src\think\Http.php(186): think\App->initialize()
#7 D:\laragon\www\blog\vendor\topthink\framework\src\think\Http.php(163): think\Http->init in D:\laragon\www\blog\vendor\topthink\framework\src\think\Container.php on line 377

**Comment by successgo** [comment]
版本回退至上一个版本呢

**Comment by hulang** [comment]
@successgo 可以。。。不知道什么问题。。反正本地测试。。

**Comment by successgo** [comment]
建议线上使用稳定版本

**Comment by hongweipeng** [comment]
看错误信息是反射出了问题
