### ISSUE TITLE
每天早上到公司开始工作打开vs code，习惯性：composer update -vvv，手贱更新6.0.8了，又和上次一样，本地挂了

### ISSUE THREAD

**Issue by hulang** [top-think/framework#2517]
https://github.com/top-think/framework/issues/2466
差不多和上次这里一样。。
更新tp版本到：6.0.8。。
我win10系统，运行环境：Laragon 4.0.16，PHP 7.2.19
日志里面错误：
[30-Apr-2021 06:42:43 UTC] PHP Fatal error:  Uncaught ReflectionException: Class think\Config does not exist in D:\laragon\www\oa\vendor\topthink\framework\src\think\Container.php:375
Stack trace:
#0 D:\laragon\www\oa\vendor\topthink\framework\src\think\Container.php(375): ReflectionClass->__construct('think\\Config')
#1 D:\laragon\www\oa\vendor\topthink\framework\src\think\Container.php(251): think\Container->invokeClass('think\\Config', Array)
#2 D:\laragon\www\oa\vendor\topthink\framework\src\think\Container.php(130): think\Container->make('think\\Config')
#3 D:\laragon\www\oa\vendor\topthink\framework\src\think\Container.php(510): think\Container->get('config')
#4 D:\laragon\www\oa\vendor\topthink\framework\src\think\App.php(542): think\Container->__get('config')
#5 D:\laragon\www\oa\vendor\topthink\framework\src\think\App.php(451): think\App->load()
#6 D:\laragon\www\oa\vendor\topthink\framework\src\think\Http.php(186): think\App->initialize()
#7 D:\laragon\www\oa\vendor\topthink\framework\src\think\Http.php(163): think\Http->initialize()
#8 D:\lar in D:\laragon\www\oa\vendor\topthink\framework\src\think\Container.php on line 377

**Comment by hulang** [comment]
退回到上一版6.0.7
