### ISSUE TITLE
模型update问题

### ISSUE THREAD

**Issue by MoeGrid** [top-think/framework#2628]
我想把某个表中的某个字段，无条件全部更新为某个值，报错

```
think\db\exception\DbException: miss update condition in /www/wwwroot/wysc.ali02.zrwsd.com/vendor/topthink/think-orm/src/db/BaseQuery.php:1044
Stack trace:
#0 /www/wwwroot/wysc.ali02.zrwsd.com/vendor/topthink/think-orm/src/Model.php(646): think\db\BaseQuery->update()
#1 /www/wwwroot/wysc.ali02.zrwsd.com/vendor/topthink/think-orm/src/db/PDOConnection.php(1418): think\Model->think\{closure}()
#2 /www/wwwroot/wysc.ali02.zrwsd.com/vendor/topthink/think-orm/src/db/concern/Transaction.php(44): think\db\PDOConnection->transaction()
#3 /www/wwwroot/wysc.ali02.zrwsd.com/vendor/topthink/think-orm/src/Model.php(654): think\db\BaseQuery->transaction()
#4 /www/wwwroot/wysc.ali02.zrwsd.com/vendor/topthink/think-orm/src/Model.php(535): think\Model->updateData()
#5 /www/wwwroot/wysc.ali02.zrwsd.com/vendor/topthink/think-orm/src/Model.php(878): think\Model->save()
#6 /www/wwwroot/wysc.ali02.zrwsd.com/app/tcp/MyWorker.php(74): think\Model::update()
```

代码

```
// 使用模型 报错
WaterDevice::update([
    'online' => 2
]);
// 使用DB 报错
Db::table('wq_water_device')->update([
    'online' => 2
]);
// 随便加个永远为真的条件就没事
WaterDevice::where('id', '>', 0)->update([
    'online' => 2
]);
```

**Comment by liu21st** [comment]
本来就是这样设计的 没有条件的时候 不会执行更新和删除操作
