### ISSUE TITLE
cache组件并发下，如果不设置模型字段缓存，会经常把报错

### ISSUE THREAD

**Issue by augushong** [top-think/framework#2968]
如下面报错，其实不用特别的高并发，用workerman开4个进程，如果有频繁的模型save，没有开启数据库字段缓存，就会频繁出现下面的报错。
```
TypeError: think\cache\driver\Redis::getTagItems(): Return value must be of type array, bool returned in /home/augushong/www/ulthon_admin/vendor/topthink/framework/src/think/cache/driver/Redis.php:233
Stack trace:
#0 /home/augushong/www/ulthon_admin/vendor/topthink/framework/src/think/cache/TagSet.php(112): think\cache\driver\Redis->getTagItems()
#1 /home/augushong/www/ulthon_admin/vendor/topthink/think-orm/src/db/PDOConnection.php(877): think\cache\TagSet->clear()
#2 /home/augushong/www/ulthon_admin/vendor/topthink/think-orm/src/db/PDOConnection.php(1167): think\db\PDOConnection->pdoExecute()
#3 /home/augushong/www/ulthon_admin/vendor/topthink/think-orm/src/db/BaseQuery.php(1260): think\db\PDOConnection->update()
#4 /home/augushong/www/ulthon_admin/vendor/topthink/think-orm/src/Model.php(673): think\db\BaseQuery->update()
#5 /home/augushong/www/ulthon_admin/vendor/topthink/think-orm/src/db/PDOConnection.php(1521): think\Model->think\{closure}()
#6 /home/augushong/www/ulthon_admin/vendor/topthink/think-orm/src/db/concern/Transaction.php(47): think\db\PDOConnection->transaction()
#7 /home/augushong/www/ulthon_admin/vendor/topthink/think-orm/src/Model.php(665): think\db\BaseQuery->transaction()
#8 /home/augushong/www/ulthon_admin/vendor/topthink/think-orm/src/Model.php(564): think\Model->updateData()
#9 /home/augushong/www/ulthon_admin/app/worker/net/worker/start.php(86): think\Model->save()
#10 /home/augushong/www/ulthon_admin/vendor/workerman/workerman/Events/Event.php(167): app\common\console\WorkerCommandConsole->{closure}()
#11 [internal function]: Workerman\Events\Event->timerCallback()
#12 /home/augushong/www/ulthon_admin/vendor/workerman/workerman/Events/Event.php(193): EventBase->loop()
#13 /home/augushong/www/ulthon_admin/vendor/workerman/workerman/Worker.php(1635): Workerman\Events\Event->loop()
#14 /home/augushong/www/ulthon_admin/vendor/workerman/workerman/Worker.php(1426): Workerman\Worker::forkOneWorkerForLinux()
#15 /home/augushong/www/ulthon_admin/vendor/workerman/workerman/Worker.php(1400): Workerman\Worker::forkWorkersForLinux()
#16 /home/augushong/www/ulthon_admin/vendor/workerman/workerman/Worker.php(1785): Workerman\Worker::forkWorkers()
#17 /home/augushong/www/ulthon_admin/vendor/workerman/workerman/Worker.php(1721): Workerman\Worker::monitorWorkersForLinux()
#18 /home/augushong/www/ulthon_admin/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#19 /home/augushong/www/ulthon_admin/app/common/console/WorkerCommandConsole.php(84): Workerman\Worker::runAll()
#20 /home/augushong/www/ulthon_admin/app/common/command/fusion/NetWorker.php(35): app\common\console\WorkerCommandConsole->execute()
#21 /home/augushong/www/ulthon_admin/vendor/topthink/framework/src/think/console/Command.php(210): app\common\command\fusion\NetWorker->execute()
#22 /home/augushong/www/ulthon_admin/vendor/topthink/framework/src/think/Console.php(649): think\console\Command->run()
#23 /home/augushong/www/ulthon_admin/vendor/topthink/framework/src/think/Console.php(308): think\Console->doRunCommand()
#24 /home/augushong/www/ulthon_admin/vendor/topthink/framework/src/think/Console.php(245): think\Console->doRun()
#25 /home/augushong/www/ulthon_admin/think(12): think\Console->run()
#26 {main}
```

**Comment by big-dream** [comment]
有点奇怪，按照 [phpredis](https://github.com/phpredis/phpredis?tab=readme-ov-file#smembers-sgetmembers) 的文档，返回类型应该只有 `array`，不应该返回 `bool`
![image](https://github.com/top-think/framework/assets/9215157/3f1fdeb2-927a-4ab2-b16d-06df16226daf)

**Comment by xieyongfa123** [comment]
我也遇到过这个问题  经过调试发现问题出在vendor\topthink\framework\src\think\cache\driver\Redis.php.  不同进程用同一个hander就会出现, 所以临时修改增加    static protected array $instance = []; //redis实例化时静态变量,防止fork多进程后数据污染    
![微信截图_20241007115518](https://github.com/user-attachments/assets/96f0d884-305f-49bf-97b2-3ff8f13ae8c1)

**Comment by augushong** [comment]
这么长时间了，再补充一下吧，当时也怀疑过时多个进程使用同一个资源造成的，所以的当时的操作是调用`Cache::forgetDriver();`

但我在新建进程中forgetDriver，不是为了解决标题的这个问题。复制进程后就需要清空，否则确实会出问题。至于字段这个问题，没有深度排查，只是开启了字段缓存。

**Comment by Muspcn** [comment]
这个问题到今天有好的解决办法吗

**Comment by Muspcn** [comment]
我开了个workman再开个kafka

workerman中使用model
kafka中使用db

字段缓存使用的是redis

依然出现save时报错Redis::getTagItems(): Return value must be of type array, bool returned

**Comment by augushong** [comment]
主动开启字段缓存吧。

最近有个思路就是实现一个进程内存内的缓存驱动，各个进程独立，对于常驻进程的场景来说能解决。

**Comment by Muspcn** [comment]
> 主动开启字段缓存吧。
> 
> 最近有个思路就是实现一个进程内存内的缓存驱动，各个进程独立，对于常驻进程的场景来说能解决。

字段缓存是开启的，我就一个workman进程，我感觉像是redis的脏数据导致tag->clear报错，因为save后调用了update，update里面调用了tag(xxx)->clear()
我现在从think-orm 3.0.14->3.0.16
看更新日志中说处理了这个问题

**Comment by Muspcn** [comment]
我还发现3.0.14的升级到3.0.33后关联的逻辑都修改了有链表的部分代码都需要修改，将原有的连表条件的别名从小驼峰改成了下划线，还不支持配置改回来，就只能用到3.0.16这个版本

**Comment by Muspcn** [comment]
我错了，目前又报错了，会是缓存驱动的问题吗，redis本身是支持并发的吧
