### ISSUE TITLE
linux主机(bluehost)部署时报错如下.

### ISSUE THREAD

**Issue by momoca** [top-think/framework#3]
```
Fatal error: Uncaught exception 'think\exception\ErrorException' with message 'mkdir(): Permission denied' in /home/test1net/test1.net/ThinkPHP/library/think/log/driver/File.php:43
Stack trace:
#0 [internal function]: think\Error::appError(2, 'mkdir(): Permis...', '/home/test1net...', 43, Array)
#1 /home/test1net/test1.net/ThinkPHP/library/think/log/driver/File.php(43): mkdir('./runtime/log/', 493, true)
#2 /home/test1net/test1.net/ThinkPHP/library/think/Log.php(95): think\log\driver\File-&gt;save(Array)
#3 /home/test1net/test1.net/ThinkPHP/library/think/Error.php(113): think\Log::save()
#4 [internal function]: think\Error::appShutdown()
#5 {main}
thrown in /home/test1net/test1.net/ThinkPHP/library/think/log/driver/File.php on line 43
```

**Comment by momoca** [comment]
乌龙了.发现是定义重了ROOT_PATH!
