### ISSUE TITLE
[TP5.0]写入日志时框架抛出ErrorException(A non well formed numeric value encount)

### ISSUE THREAD

**Issue by littlerun** [top-think/framework#380]
### 遇到的问题是什么？
1）在TP5.0当中，使用Log::write方法循环写入日志时（开启了一个while true循环的脚本作为服务），框架抛出ErrorException异常
2）脚本以console Command方式运行，通过try...catch无法捕获到该异常

### 如何重现此问题?
（此错误不能稳定重现，但每天都会报出几条，可以算频繁出现）

1) 创建命令行脚本，循环写入日志

``` php
class Pay extends Command {
    
    protected function configure()
    {
        $this->setName('pay')->setDescription('The payment service scripts,that run as the daemon process.');
    }

    protected function execute(Input $input, Output $output)
    {
        $this->output = $output;
        
        $this->initService();
        while(true) {
            try {
                Log::write("支付服务处理开始");
                $this->output->writeln("Starting the payment process...");
                $orderPayTaskProduct = new PayTaskProductLogic();
                $orderPayTaskProduct->handle();
                Log::write("服务处理结束");
                $this->output->writeln("The payment process was finished.");
            } catch (think\exception\ErrorException $ex) {
                ...
            }
            sleep ( $seconds = 2 );
        }

        $this->stopService();        
    }
}
```

2) 注册脚本到command.php

``` php
//命令行配置
return [
    //配置命令行的命名空间。
    'app\sslscript\Pay',
	...
```

3) 执行该脚本
``` bash
> php think pay
```

### 期望结果是什么?

脚本稳定运行，并输出日志到指定的日志文件当中。

### 实际结果是什么?

一个think\exception\ErrorException异常被抛出，且没有被try...catch捕获。
异常信息:
``` php
PHP Fatal error:  Uncaught exception 'think\exception\ErrorException' with message 'A non well formed numeric value encountered' in /home/ops/script/thinkphp/library/think/log/driver/File.php:62
Stack trace:
#0 [internal function]: think\Error::appError(8, 'A non well form...', '/home/ops/scrip...', 62, Array)
#1 /home/ops/script/thinkphp/library/think/log/driver/File.php(62): number_format('1,001.034633874...', 6)
#2 /home/ops/script/thinkphp/library/think/Log.php(149): think\log\driver\File->save(Array)
#3 /home/ops/script/thinkphp/library/think/Error.php(84): think\Log::save()
#4 [internal function]: think\Error::appShutdown()
#5 {main}
  thrown in /home/ops/script/thinkphp/library/think/log/driver/File.php on line 62

```
从异常信息中的对应代码：
thinkphp/library/think/log/driver/File.php：62行
```php
$time_str   = ' [运行时间：' . number_format($runtime, 6) . 's][吞吐率：' . $reqs . 'req/s]';
```
### 临时解决办法

在第60行获取runtime时，不要使用number_format，因为超过1000时会变为字符串"1,000"
```php
// $runtime    = number_format(microtime(true) - THINK_START_TIME, 10);
$runtime    = microtime(true) - THINK_START_TIME;
```
### 其他信息

这个问题在本地和服务器都会重现

| Q | A |
| --- | --- |
| ThinkPHP 版本 | 5.0 |
| PHP 版本 | 5.6.27 |
| 操作系统 | CentOS release 6.2 |

**Comment by kinosang** [comment]
推荐尝试使用队列来完成本工作。`while(true)`的方法不被推荐。

**Comment by littlerun** [comment]
@kinosang 感谢您的回复，学习了。我们后续会更新为 topthink/think-queue。
