### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by cnsms** [top-think/framework#723]
2017-07-05 10:02:23 exception 'PDOException' with message 'SQLSTATE[08004] [1040] Too many connections' in C:\www\zk\thinkphp\library\think\db\Connection.php:300
Stack trace:
#0 C:\www\zk\thinkphp\library\think\db\Connection.php(300): PDO->__construct('mysql:dbname=do...', 'root', 'root', Array)
#1 C:\www\zk\thinkphp\library\think\db\Connection.php(934): think\db\Connection->connect()
#2 C:\www\zk\thinkphp\library\think\db\Connection.php(357): think\db\Connection->initConnect(false)
#3 C:\www\zk\thinkphp\library\think\db\Query.php(225): think\db\Connection->query('SELECT * FROM `...', Array, false, false)
#4 C:\www\zk\thinkphp\library\think\db\Query.php(2445): think\db\Query->query('SELECT * FROM `...', Array, false, false)
#5 C:\www\zk\application\workerman\model\Data.php(63): think\db\Query->find()
#6 C:\www\zk\application\workerman\controller\Index.php(83): app\workerman\model\Data->send(22)
#7 [internal function]: app\workerman\controller\Index->app\workerman\controller\{closure}(Object(Workerman\Connection\TcpConnection), '\xFF\xAA\x16\x00\\\x00000000000...')
#8 C:\www\zk\Workerman\Connection\TcpConnection.php(503): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '\xFF\xAA\x16\x00\\\x00000000000...')
#9 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #77)
#10 C:\www\zk\Workerman\Events\Select.php(257): call_user_func_array(Array, Array)
#11 C:\www\zk\Workerman\Worker.php(809): Workerman\Events\Select->loop()
#12 C:\www\zk\Workerman\Worker.php(457): Workerman\Worker->run()
#13 C:\www\zk\Workerman\Worker.php(366): Workerman\Worker::runAllWorkers()
#14 C:\www\zk\application\workerman\controller\Index.php(126): Workerman\Worker::runAll()
#15 [internal function]: app\workerman\controller\Index->index()
#16 C:\www\zk\thinkphp\library\think\App.php(224): ReflectionMethod->invokeArgs(Object(app\workerman\controller\Index), Array)
#17 C:\www\zk\thinkphp\library\think\App.php(389): think\App::invokeMethod(Array, Array)
#18 C:\www\zk\thinkphp\library\think\App.php(130): think\App::module(Array, Array, NULL)
#19 C:\www\zk\thinkphp\start.php(18): think\App::run()
#20 C:\www\zk\index.php(32): require('C:\\www\\zk\\think...')
#21 {main}

**Comment by cnsms** [comment]
是哪里应该断开连接的地方没有断开吧？
